language: php

php:
  - 7.1

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=vendor/ondrejbouda/coding-standard/src/ruleset.xml --extensions=php --encoding=utf-8 --tab-width=4 -sp src tests
  - vendor/bin/phpstan analyse --level 4 -c tests/phpstan.neon src tests
  - vendor/bin/phpunit
